# Generated by Django 5.0 on 2023-12-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('naixement', models.DateField(blank=True, null=True)),
                ('mort', models.DateField(blank=True, null=True, verbose_name='mort')),
                ('premis', models.IntegerField(help_text='Escriu el número de premis que ha guanyat.')),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Escriu el gènere de música (Ex: Pop, K-pop, Rock...)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('duració', models.IntegerField(help_text='Escriu la duració total del àlbum')),
                ('preu', models.IntegerField(help_text="Escriu el preu de l'àlbum")),
                ('cantant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioteca.cantant')),
                ('genere', models.ManyToManyField(help_text='Selecciona un gènere per a aquest àlbum.', to='audioteca.genere')),
            ],
        ),
        migrations.CreateModel(
            name='Canço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('duració', models.IntegerField(help_text='Escriu la duració de al cançó')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioteca.album')),
                ('cantant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioteca.cantant')),
            ],
        ),
    ]
