# Generated by Django 5.0 on 2023-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantant',
            name='descripcio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
