# Generated by Django 5.0 on 2023-12-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioteca', '0003_rename_genere_album_generes'),
    ]

    operations = [
        migrations.AddField(
            model_name='canço',
            name='lletres',
            field=models.TextField(null=True),
        ),
    ]
