# Generated by Django 5.0 on 2023-12-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioteca', '0004_canço_lletres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canço',
            old_name='lletres',
            new_name='lletra',
        ),
    ]
