# Generated by Django 5.0 on 2023-12-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioteca', '0005_rename_lletres_canço_lletra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantant',
            name='imatge',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
