# Generated by Django 5.0 on 2023-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioteca', '0020_alter_cantant_imatge'),
    ]

    operations = [
        migrations.AddField(
            model_name='canço',
            name='video',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
