# Generated by Django 5.0 on 2023-12-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioteca', '0021_canço_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='portada',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='canço',
            name='video',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
